// @ts-nocheck
import { HEROES } from '../data/heroes';
import { G } from './state';
import { buildSnapshot } from '../sim/engine';
import { addToast } from '../render/fx';

export const Store = {
  ok: (()=>{ try{ localStorage.setItem('lb.t','1'); localStorage.removeItem('lb.t'); return true; }
             catch(e){ return false; } })(),
  get(k, d){ try{ const v = localStorage.getItem(k); return v ? JSON.parse(v) : d; } catch(e){ return d; } },
  set(k, v){ try{ localStorage.setItem(k, JSON.stringify(v)); return true; } catch(e){ return false; } }
};
export const HIST_KEY = 'lb.history', NAME_KEY = 'lb.name', HIST_MAX = 600;
export function history(){ const h = Store.get(HIST_KEY, []); return Array.isArray(h) ? h : []; }
export function saveHistory(h){
  if (h.length > HIST_MAX) h = h.slice(h.length - HIST_MAX);
  Store.set(HIST_KEY, h);
}
/* One finished match, written by every player who was in it. The id is generated by
   the host and shared, so importing a friend's export merges instead of duplicating. */
export function recordMatch(v, winner){
  // fall back to the last raw snapshot, or rebuild one, so a result is never lost
  v = v || G.latest || (G.S ? buildSnapshot(G.S, G.myTeam) : null);
  if (!v || !v.ps || G.mode==='local') return;          // practice games are not history
  const id = G.matchId || ('m'+Date.now());
  if (G.recorded === id) return;
  G.recorded = id;
  const rec = {
    id: id, ts: Date.now(), mode: v.md || '1v1',
    dur: Math.round(v.t), how: v.hw || '', win: winner, me: G.mySlot,
    ps: v.ps.map(q=>({sl:q.sl, tm:q.tm, nm:q.nm || ('Player '+(q.sl+1)), h:q.hid,
                      k:q.k, d:q.d, a:q.as||0, cs:q.cs, dn:q.dn, lvl:q.lvl, nw:q.nw}))
  };
  const h = history();
  if (!h.some(r=>r.id===rec.id)) h.push(rec);
  saveHistory(h);
}
/* ---- the numbers the stats screen shows ---- */
export function statsFor(hist){
  const me = {games:0, wins:0, k:0, d:0, a:0, cs:0, dn:0, dur:0};
  const heroes = {}, foes = {}, mates = {};
  for (const r of hist){
    const mine = r.ps.find(q=>q.sl===r.me); if (!mine) continue;
    const won = mine.tm === r.win;
    me.games++; me.wins += won?1:0;
    me.k+=mine.k; me.d+=mine.d; me.a+=mine.a; me.cs+=mine.cs; me.dn+=mine.dn; me.dur+=r.dur;
    const H = heroes[mine.h] = heroes[mine.h] || {g:0,w:0,k:0,d:0,a:0,cs:0};
    H.g++; H.w+=won?1:0; H.k+=mine.k; H.d+=mine.d; H.a+=mine.a; H.cs+=mine.cs;
    for (const q of r.ps){
      if (q.sl===mine.sl) continue;
      const bag = q.tm===mine.tm ? mates : foes;
      const E = bag[q.nm] = bag[q.nm] || {g:0,w:0};
      E.g++; E.w += won?1:0;
    }
  }
  return {me, heroes, foes, mates};
}
export function pct(w,g){ return g? Math.round(w/g*100)+'%' : '—'; }
export function fmtDate(ts){
  const d = new Date(ts);
  return d.toLocaleDateString(undefined,{month:'short',day:'numeric'})+' '+
         d.toLocaleTimeString(undefined,{hour:'2-digit',minute:'2-digit'});
}
/* History outlives the roster — records can hold hero ids that were since
   renamed or retired (and imports can carry ids from other versions). */
function heroRef(id){
  return HEROES[id] || {name:(id||'?').toUpperCase()+' (retired)', col:'#9aa4b8'};
}
export function renderStats(){
  const box = document.getElementById('statsBody');
  const hist = history().slice().sort((a,b)=>b.ts-a.ts);
  if (!Store.ok){
    box.innerHTML = '<div class="note" style="color:var(--red)">This browser is blocking local storage, '+
      'so history cannot be saved. Opening the file over <b>http://</b> instead of double-clicking it '+
      'usually fixes this.</div>';
    return;
  }
  if (!hist.length){
    box.innerHTML = '<div class="note">No games recorded yet. Play an online match and it will show up here. '+
      'Practice games are not recorded.</div>';
    return;
  }
  const S2 = statsFor(hist), m = S2.me;
  const avg = (n)=> m.games ? (n/m.games).toFixed(1) : '0';
  let html = '<div class="scards">'+
    card('Games', m.games) +
    card('Record', m.wins+' – '+(m.games-m.wins)) +
    card('Win rate', pct(m.wins, m.games)) +
    card('Avg K/D/A', avg(m.k)+' / '+avg(m.d)+' / '+avg(m.a)) +
    card('Avg last hits', avg(m.cs)) +
    card('Time played', Math.round(m.dur/60)+' min') +
    '</div>';

  const heroRows = Object.entries(S2.heroes).sort((a,b)=>b[1].g-a[1].g).map(([h,v])=>
    '<tr><td style="color:'+heroRef(h).col+';font-weight:800">'+heroRef(h).name+'</td>'+
    '<td>'+v.g+'</td><td>'+v.w+' – '+(v.g-v.w)+'</td><td>'+pct(v.w,v.g)+'</td>'+
    '<td>'+(v.k/v.g).toFixed(1)+' / '+(v.d/v.g).toFixed(1)+' / '+(v.a/v.g).toFixed(1)+'</td>'+
    '<td>'+(v.cs/v.g).toFixed(0)+'</td></tr>').join('');
  html += '<h3>By hero</h3><table class="stab"><tr><th>Hero</th><th>Games</th><th>W–L</th>'+
          '<th>Win%</th><th>Avg K/D/A</th><th>Avg CS</th></tr>'+heroRows+'</table>';

  const foeRows = Object.entries(S2.foes).sort((a,b)=>b[1].g-a[1].g).map(([n,v])=>
    '<tr><td style="font-weight:700">'+n+'</td><td>'+v.g+'</td>'+
    '<td>'+v.w+' – '+(v.g-v.w)+'</td><td>'+pct(v.w,v.g)+'</td></tr>').join('');
  if (foeRows) html += '<h3>Against</h3><table class="stab"><tr><th>Player</th><th>Games</th>'+
                       '<th>Your record</th><th>Win%</th></tr>'+foeRows+'</table>';

  const mateRows = Object.entries(S2.mates).sort((a,b)=>b[1].g-a[1].g).map(([n,v])=>
    '<tr><td style="font-weight:700">'+n+'</td><td>'+v.g+'</td>'+
    '<td>'+v.w+' – '+(v.g-v.w)+'</td><td>'+pct(v.w,v.g)+'</td></tr>').join('');
  if (mateRows) html += '<h3>Alongside</h3><table class="stab"><tr><th>Player</th><th>Games</th>'+
                        '<th>Record together</th><th>Win%</th></tr>'+mateRows+'</table>';

  html += '<h3>Recent matches</h3><table class="stab">'+
    '<tr><th>When</th><th>Mode</th><th>Result</th><th>You</th><th>K/D/A</th><th>CS</th><th>Lineup</th></tr>'+
    hist.slice(0,40).map(r=>{
      const mine = r.ps.find(q=>q.sl===r.me) || r.ps[0];
      const won = mine.tm===r.win;
      const line = r.ps.filter(q=>q.sl!==mine.sl)
                      .map(q=>'<span style="color:'+(q.tm===mine.tm?'var(--acc)':'var(--red)')+'">'+
                              q.nm+' ('+heroRef(q.h).name+')</span>').join(', ');
      return '<tr><td>'+fmtDate(r.ts)+'</td><td>'+r.mode.toUpperCase()+'</td>'+
             '<td style="color:'+(won?'var(--acc)':'var(--red)')+';font-weight:800">'+(won?'WIN':'LOSS')+'</td>'+
             '<td style="color:'+heroRef(mine.h).col+'">'+heroRef(mine.h).name+'</td>'+
             '<td>'+mine.k+'/'+mine.d+'/'+mine.a+'</td><td>'+mine.cs+'</td><td>'+line+'</td></tr>';
    }).join('')+'</table>';
  box.innerHTML = html;
}
export function card(label, val){
  return '<div class="scard"><div class="sv">'+val+'</div><div class="sl">'+label+'</div></div>';
}
export function exportHistory(){
  const blob = new Blob([JSON.stringify({app:'lanebreaker', v:1, name:G.name, matches:history()}, null, 1)],
                        {type:'application/json'});
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = 'lanebreaker-history-'+new Date().toISOString().slice(0,10)+'.json';
  a.click();
  setTimeout(()=>URL.revokeObjectURL(a.href), 4000);
}
export function importHistory(input){
  const f = input.files && input.files[0];
  if (!f) return;
  const fr = new FileReader();
  fr.onload = ()=>{
    try{
      const data = JSON.parse(fr.result);
      const incoming = Array.isArray(data) ? data : (data.matches||[]);
      const h = history();
      const seen = new Set(h.map(r=>r.id));
      let added = 0;
      for (const r of incoming) if (r && r.id && !seen.has(r.id)){ h.push(r); seen.add(r.id); added++; }
      h.sort((a,b)=>a.ts-b.ts);
      saveHistory(h);
      renderStats();
      addToast('Imported '+added+' new match'+(added===1?'':'es'));
    }catch(e){ addToast('Could not read that file'); }
    input.value='';
  };
  fr.readAsText(f);
}
export function clearHistory(){
  if (!confirm('Delete every recorded match on this computer?')) return;
  Store.set(HIST_KEY, []);
  renderStats();
}

